export enum ACTION_TYPES{
    ADD_POST = 'ADD_POST',
    FETCH_TOP_POSTS = 'FETCH_TOP_POSTS',
    FETCH_NEXT_SET = 'FETCH_NEXT_SET',
    FETCH_COMMENTS = 'FETCH_COMMENT',
    ADD_COMMENT = 'ADD_COMMENT'
};